### PR TITLE
adding template for file upload field with FormUI, this should fix #647

### PR DESCRIPTION
**Pull request by medmen**
adding template for file upload field with FormUI, this should fix #647
additional attributes (e.g. for multifile upload) can be passed to template

### CODE REVIEW

**Comment by Konzertheld** [comment]
I think even the type does not need to be specified in the template. At least the password control does not have it and still does have type="password". It's propably defined in the control itself somewhere.

Also, another hint, issues have to referenced like this to work: habari/habari#647 because we have them in the habari repo and not in the system repo.

**Comment by medmen** [comment]
Thanks for your input and help, as always! Will try to remember linking to issues correctly (if you have any tips how to automate things like that in PHPStorm i'd be happy to read them on irc).
About the type-field: 
the FormControlPassword extends FormControlText and sets its type by design in 
/system/controls/formcontrolpassword.php (see function _extend)

FormControlFile extends FormControl and does not set the type in source code, so as it seems the template needs the type set. 
One could argue to set type in /system/controls/formcontrolfile.php the same way as several other formcontrols do. That would make sense only (at least to me) if we found a way to point all formcontrols that build an input-field to point to a single template file.
Maybe that is a nice TODO for 0.11 :)

**Comment by Konzertheld** [comment]
I don't really use PHPStorm, so no idea on that. @ringmaster might know something.

I still do not get what stands against setting the control type from the control class as in FormControlText? Seems perfectly reasonable to me to do it the exact same way for FormControlFile. The control classes are not static, feel free to change them. :) I think doing so makes more sense than introducing one more way (hardcoding into the template). Also, the type should not be a template matter - be aware that templates may be exchanged, but file controls should always be of type file.

For unifying templates, see habari/habari#388.

**Comment by Konzertheld** [comment]
And by the way, I like it that we can have constructive discussion about this. :)

**Pull request closed without merging**
