### PR TITLE
a touch friendly admin menu, adresses issue #230

### PR DESCRIPTION
**Pull request by medmen**
- this adds a few kb of js code to detect events triggered by mobile devices like "tap" doubletap" and "swipe"
- the tap-event ist then used to alter css-classes of the admin-menu in order to make it work on mobile as one would expect
 - pro: no extra changes necessary to php or css, the js introduced will sure come in handy in other places when enhancing mobile-friendliness

### CODE REVIEW

**Comment by Konzertheld** [comment]
Nice, thanks for checking this out! I tried it and it works okay, I noticed a glitch where tapping the current page's title (which is what you see in the menu when the menu is closed) reloads the page. That does only happen for pages that have subpages. Example: Go to Manage - Pages. Menu will then be titled "Manage Posts". Tap "Manage Posts". Menu does not open instead page reloads.

Apart from that, I appreciate that approach. We can really use improvements in that field, and in case we discover a solution without external JS, we can remove this code later.

**Comment by medmen** [comment]
Sorry, i tried but could not reproduce the glitch you describe on 2 different devices (both using firefox). 
Actually line 124 in admin.js is supposed to suppress just this behavior by firing "preventDefault()", but all actions are attached to an anchor-tag "<a >", so in theory events bound to parent tags might fire and cause this behaviour - i just didnt find any...
I could add a few console-log entries if that helps catching the glitch..

**Comment by Konzertheld** [comment]
I discovered that glitch on Chrome, that might be the issue. Also I think I remember preventDefault() being deprecated, but that is just a shadow of a memory and I would need to google that myself.

**Comment by Konzertheld** [comment]
I now checked on Firefox and while the glitch I described does not appear there, I found another one: When you are on the manage page, tap the menu, then tap "Manage" (no matter if the word or the arrow) - page will reload before you get a chance to choose from the submenu.

**Comment by Konzertheld** [comment]
I would additionally like to note we might be able to make the menu mobile-friendly without new code. We have formcontrols called Dropbuttons, they are used on the manage pages for the edit/delete actions. They work on mobile. They do not support submenus, but could be extended to do so without much work.

**Pull request closed without merging**
