### PR TITLE
Bugfix for PHP7 and minor other fixes

### PR DESCRIPTION
**Pull request by medmen**
1. Fix in classes/error.php make Habari run under PHP7
2. Corrected tag-names in admin/js/admin.js to insert Images at correct location 
3. Small CSS-fix makes images in Media-Panel line up horizontally again (result is not perfect though)
4. Fixed configure theme functionality by including necessary js file

Note: I am kind of new to git-stuff so i hope i did everything correct...

### CODE REVIEW

**Comment by Konzertheld** [comment]
I don't get what the last commit "undo recent changes in db_setup.php - the problem was missing themes..." does. It reverts my namespace changes which are clearly necessary. It also changes the submodule commits which has nothing to do with what the commit message states.

**Comment by Konzertheld** [comment]
You mention you are new to Git, so maybe the submodule thing was by accident?

**Comment by medmen** [comment]
Yes, the whole last commit is nonsense and I am to stupid to remove it from my pull request - please simply forget about that one. Sorry..

**Comment by Konzertheld** [comment]
No problem. What about the submodule changes (in the same commit)?

And for the future, it is easier for you and us if you make changes in a branch and then request to pull that branch instead of using your copy of master.

**Comment by Konzertheld** [comment]
That's another reason - all your commits automatically go here, if they were in a branch, you could separate them into multiple pull requests. That way we could include them faster.

**Comment by medmen** [comment]
Mist. I should really learn git. Sorry about that, i will start using branches asap.

**Comment by Konzertheld** [comment]
Kein Problem ;) No worries, you don't want to know what I messed up when I started. If you need help with Git, feel free to ask in IRC. Also, for most of the things, there are good answers on StackOverflow.

So, to get this request done, you could move the commits you really wanted to put in the pull request to a branch now (it's not too late). And then make a pull request for that branch, and then I will close this one so we don't mess things up.

**Comment by medmen** [comment]
@Konzertheld: i see you tackled the php7-issue in you pull-request also.
So to clean up this mess, I will close this pull request and do as you suggested - branch and commit the few things left :)

**Comment by Konzertheld** [comment]
Ok great. :)

**Pull request closed without merging**
